import { createContext, useCallback, useContext, useEffect, useRef, useState } from "react";
import { useOptionsTranslation } from "../../../../../lib/hooks/useOptionsTranslate";
import { useAuth } from "../../../../../lib/providers/auth-provider";
import { useGlobalContext } from "../../../../../lib/providers/global-provider";
import {
  AffiliateVideoFormConfig,
  CACHE_KEY,
  DB_NAME,
  ScriptData,
  STORE_NAME,
  StoryModeTypeEnum,
  TrendingHistoryItem,
  TrendingModeTypeEnum,
  TrendingScriptData,
  TrendingVideoFormConfig,
  withoutPromptSelection,
} from "../../constants";
import { GenerateSceneFromTextParams } from "../../copy-video/hook/useCopyVideoApi";
import { useAffiliateVideoApi } from "../../hook/useAffiliateVideoApi";
import { useIndexedDB } from "../../hook/useIndexedDB";
import {
  SceneErrorKind,
  SceneErrors,
  useSceneErrorBroadcast,
} from "../../hook/useSceneErrorBroadcast";
import {
  SceneProgress,
  SceneProgressKind,
  useSceneProgressBroadcast,
} from "../../hook/useSceneProgressBroadcast";
import { syncSidebarPatchToCurrentScript } from "../../shared/syncSidebarPatchToCurrentScript";

/** Key used to persist the last generated script in IndexedDB */

export const AffiliateVideoContext = createContext<
  Partial<{
    modeTab: ModeTab;
    setModeTab: (modeTab: ModeTab) => void;
    speed: SpeedMode | string;
    setSpeed: (speed: SpeedMode | string) => void;
    delayQueue: DelayQueue;
    setDelayQueue: (delayQueue: DelayQueue) => void;
    searchQuery: string;
    setSearchQuery: (searchQuery: string) => void;
    voiceMode: VoiceMode;
    setVoiceMode: (voiceMode: VoiceMode) => void;
    videoConfig: TrendingVideoFormConfig;
    setVideoConfig: (videoConfig: AffiliateVideoFormConfig) => void;
    showAiModal: boolean;
    setShowAiModal: (showAiModal: boolean) => void;
    batchRunning: boolean;
    setBatchRunning: (batchRunning: boolean) => void;
    activeTab: MainTab;
    setActiveTab: (activeTab: MainTab) => void;

    zoomSrc: { src: string; type: "image" | "video" } | null;
    setZoomSrc: (zoomSrc: { src: string; type: "image" | "video" } | null) => void;
    stopRef: React.MutableRefObject<boolean>;
    SpeedModeOptions?: { label: string; value: SpeedMode | string }[];
    DelayQueueOptions?: { label: string; value: DelayQueue | string }[];
    ModeTabOptions?: { label: string; value: ModeTab | string }[];
    MainTabOptions?: { label: string; value: MainTab | string }[];
    VoiceModeOptions?: { label: string; value: VoiceMode | string }[];
    VideoCountOptions?: { label: string; value: number }[];
    totalCount: number;
    doneCount: number;
    patchConfig: (p: Partial<TrendingVideoFormConfig>) => void;

    useMock: boolean;
    genCount: number;
    histCount: number;

    /** Convenience getter – returns current form values as AffiliateFormConfig */
    affiliateFormConfig: AffiliateVideoFormConfig;
    // ── Script data ──
    scriptData: TrendingScriptData | null;
    setScriptData: (data: TrendingScriptData | null) => void;
    scriptTab: "script" | "batch" | "prompt-rank";
    setScriptTab: (tab: "script" | "batch" | "prompt-rank") => void;
    batchList: string[];
    setBatchList: (list: string[]) => void;
    handleSubmit: (data: TrendingVideoFormConfig, promptText?: string) => void;
    generateSceneFromText: (params: GenerateSceneFromTextParams) => Promise<ScriptData | undefined>;
    affiliateVideoFormConfig: TrendingVideoFormConfig;
    setAffiliateVideoFormConfig: (videoConfig: TrendingVideoFormConfig) => void;
    defaultVideoConfig: TrendingVideoFormConfig;
    /** Ref holding scene IDs currently being generated by batch process */
    batchGeneratingSceneIdsRef: React.MutableRefObject<Set<string>>;
    /** Add a scene ID to the batch-generating set */
    addBatchGeneratingSceneId: (id: string) => void;
    /** Remove a scene ID from the batch-generating set */
    removeBatchGeneratingSceneId: (id: string) => void;
    /** Ref holding scene IDs currently generating video by batch process */
    batchGeneratingVideoSceneIdsRef: React.MutableRefObject<Set<string>>;
    /** Add a scene ID to the batch-video-generating set */
    addBatchGeneratingVideoSceneId: (id: string) => void;
    /** Remove a scene ID from the batch-video-generating set */
    removeBatchGeneratingVideoSceneId: (id: string) => void;
    /** Subscribe to batch generating state changes for a specific scene */
    subscribeBatchState: (
      sceneId: string,
      callback: (
        generating: boolean,
        generatingVideo: boolean,
        generatingExtendVideo: boolean
      ) => void
    ) => () => void;
    /** Báo lỗi inline cho 1 scene (dùng cho batch/single generation) */
    reportSceneError: (sceneId: string, kind: SceneErrorKind, message: string | null) => void;
    /** Subscribe state lỗi inline cho 1 scene */
    subscribeSceneError: (sceneId: string, callback: (errors: SceneErrors) => void) => () => void;
    getSceneErrors: (sceneId: string) => SceneErrors;
    reportSceneProgress: (
      sceneId: string,
      kind: SceneProgressKind,
      progress: number | null
    ) => void;
    subscribeSceneProgress: (
      sceneId: string,
      callback: (progress: SceneProgress) => void
    ) => () => void;

    // ── Scene history ──
    /** Full history list (newest first) */
    sceneHistory: TrendingHistoryItem[];
    /** Currently selected history item ID (null = latest / no history) */
    selectedHistoryId: string | null;
    /** Select a history item by ID and apply its data */
    selectHistoryItem: (id: string) => void;
    /** Clear all scene generation history */
    clearSceneHistory: () => Promise<void>;
    /** Refresh history from IndexedDB */
    refreshSceneHistory: () => Promise<void>;

    storyModeType: StoryModeTypeEnum;
    setStoryModeType: (storyModeType: StoryModeTypeEnum) => void;
    trendingModeType: TrendingModeTypeEnum;
    setTrendingModeType: (trendingModeType: TrendingModeTypeEnum) => void;

    /** Pending prompt set by "Dùng ngay" button, consumed by AffiliateConfig */
    pendingPrompt: string | null;
    setPendingPrompt: (prompt: string | null) => void;
    trendingScriptData: TrendingScriptData | null;
    setTrendingScriptData: (data: TrendingScriptData | null) => void;

    /** Open the left sidebar (mobile) – triggered by "Dùng ngay" */
    openSidebar: () => void;
  }>
>({});

export function AffiliateVideoProvider(props: {
  children: React.ReactNode;
  openSidebar?: () => void;
}) {
  const {
    generateTrendingScene,
    generateTrendingSingle,
    getTrendingSceneHistory,
    clearTrendingHistory: clearTrendingHistoryApi,
  } = useAffiliateVideoApi();
  const { customer } = useAuth();
  const { setOpenCustomerLoginDialog } = useGlobalContext();
  const [searchQuery, setSearchQuery] = useState("");
  const stopRef = useRef(false);

  // ── IndexedDB – shared cache for AI results ──
  const scriptDB = useIndexedDB<any>(STORE_NAME.generateScene, DB_NAME.generateScene);

  // ── Script / Batch state ──
  const [trendingScriptData, setTrendingScriptData] = useState<TrendingScriptData | null>(null);
  const [scriptTab, setScriptTab] = useState<"script" | "batch" | "prompt-rank">("script");
  const [batchList, setBatchList] = useState<string[]>(["Kịch bản 1"]);
  const [batchRunning, setBatchRunning] = useState(false);
  // ── Batch generating state: refs + per-scene subscriptions ──
  // Using refs instead of state to avoid re-rendering ALL context consumers
  // when a single scene's batch state changes.
  const batchGeneratingSceneIdsRef = useRef<Set<string>>(new Set());
  const batchGeneratingVideoSceneIdsRef = useRef<Set<string>>(new Set());
  const batchSubscribersRef = useRef<
    Map<
      string,
      (generating: boolean, generatingVideo: boolean, generatingExtendVideo: boolean) => void
    >
  >(new Map());

  // ── Per-scene inline error broadcast (batch generation failures) ──
  const { reportSceneError, subscribeSceneError, getSceneErrors } = useSceneErrorBroadcast();
  const { reportSceneProgress, subscribeSceneProgress } = useSceneProgressBroadcast();

  const [storyModeType, setStoryModeType] = useState<StoryModeTypeEnum>(
    StoryModeTypeEnum.image_to_video
  );
  const [trendingModeType, setTrendingModeType] = useState<TrendingModeTypeEnum>(
    TrendingModeTypeEnum.single_variant
  );

  // ── Scene history state ──
  const [trendingHistory, setTrendingHistory] = useState<TrendingHistoryItem[]>([]);
  const [selectedTrendingHistoryId, setSelectedTrendingHistoryId] = useState<string | null>(null);

  // Pending prompt: bridge between TrendingCategoryList and AffiliateConfig
  const [pendingPrompt, setPendingPrompt] = useState<string | null>(null);

  /** Notify a scene's subscriber of its current batch state */
  const notifySubscriber = useCallback((sceneId: string) => {
    // Extract base scene ID (strip ::stitch suffix)
    const baseId = sceneId.replace(/::stitch$/, "");
    const cb = batchSubscribersRef.current.get(baseId);
    if (cb) {
      cb(
        batchGeneratingSceneIdsRef.current.has(baseId),
        batchGeneratingVideoSceneIdsRef.current.has(baseId),
        batchGeneratingVideoSceneIdsRef.current.has(baseId + "::stitch")
      );
    }
  }, []);

  /** Subscribe to batch state changes for a specific scene */
  const subscribeBatchState = useCallback(
    (
      sceneId: string,
      callback: (
        generating: boolean,
        generatingVideo: boolean,
        generatingExtendVideo: boolean
      ) => void
    ) => {
      batchSubscribersRef.current.set(sceneId, callback);
      // Immediately notify with current state
      callback(
        batchGeneratingSceneIdsRef.current.has(sceneId),
        batchGeneratingVideoSceneIdsRef.current.has(sceneId),
        batchGeneratingVideoSceneIdsRef.current.has(sceneId + "::stitch")
      );
      return () => {
        batchSubscribersRef.current.delete(sceneId);
      };
    },
    []
  );

  const addBatchGeneratingSceneId = useCallback(
    (id: string) => {
      batchGeneratingSceneIdsRef.current.add(id);
      notifySubscriber(id);
    },
    [notifySubscriber]
  );

  const removeBatchGeneratingSceneId = useCallback(
    (id: string) => {
      batchGeneratingSceneIdsRef.current.delete(id);
      notifySubscriber(id);
    },
    [notifySubscriber]
  );

  const addBatchGeneratingVideoSceneId = useCallback(
    (id: string) => {
      batchGeneratingVideoSceneIdsRef.current.add(id);
      notifySubscriber(id);
    },
    [notifySubscriber]
  );

  const removeBatchGeneratingVideoSceneId = useCallback(
    (id: string) => {
      batchGeneratingVideoSceneIdsRef.current.delete(id);
      notifySubscriber(id);
    },
    [notifySubscriber]
  );

  const {
    DEFAULT_TRENDING_VIDEO_CONFIG,
    SPEED_MODE_OPTIONS,
    DELAY_QUEUE_OPTIONS,
    MODE_TAB_OPTIONS,
    MAIN_TAB_OPTIONS,
    VOICE_MODE_OPTIONS,
    VIDEO_COUNT_OPTIONS,
  } = useOptionsTranslation();
  const [affiliateVideoFormConfig, setAffiliateVideoFormConfig] = useState<TrendingVideoFormConfig>(
    DEFAULT_TRENDING_VIDEO_CONFIG
  );

  // ── On mount: restore last cached script + config from IndexedDB ──
  useEffect(() => {
    if (customer?._id) {
      getTrendingSceneList();
      restoreConfigFromDB();
      refreshTrendingHistory();
    }
  }, [customer?._id]);

  /** Refresh history list from IndexedDB */
  const refreshTrendingHistory = useCallback(async () => {
    try {
      const history = await getTrendingSceneHistory();
      setTrendingHistory(history);
    } catch (err) {
      console.warn("[affiliate-video] Failed to load scene history", err);
    }
  }, [getTrendingSceneHistory]);

  /** Select a history item by ID and apply its data to scriptData */
  const selectTrendingHistoryItem = useCallback(
    (id: string) => {
      const item = trendingHistory.find((h) => h.id === id);
      if (item) {
        setSelectedTrendingHistoryId(id);
        setTrendingScriptData(item.data);
        // Also update lastScript so it persists across page reloads
        scriptDB.set(CACHE_KEY.lastTrendingScript, item.data).catch(() => {});
      }
    },
    [trendingHistory, scriptDB]
  );

  /** Clear all history */
  const clearTrendingHistoryFn = useCallback(async () => {
    await clearTrendingHistoryApi();
    setTrendingHistory([]);
    setSelectedTrendingHistoryId(null);
  }, [clearTrendingHistoryApi]);

  const getTrendingSceneList = async () => {
    try {
      const cached = await scriptDB.get(CACHE_KEY.lastTrendingScript);
      if (cached) {
        setTrendingScriptData(cached);
      }
    } catch (err) {
      console.warn("[affiliate-video] IndexedDB read error", err);
    }
  };

  /** Restore form config from IndexedDB; fall back to DEFAULT_VIDEO_CONFIG */

  const restoreConfigFromDB = async () => {
    try {
      const cachedConfig = await scriptDB.get(CACHE_KEY.trendingInput);
      if (cachedConfig) {
        const restored = withoutPromptSelection(cachedConfig);
        setAffiliateVideoFormConfig(restored);
        persistConfig(restored);
      }
    } catch (err) {
      console.warn("[affiliate-video] Failed to restore config from IndexedDB", err);
    }
  };

  const handleSubmit = async (data: TrendingVideoFormConfig, promptText?: string) => {
    if (!customer) {
      setOpenCustomerLoginDialog(true);
      return;
    }
    try {
      setScriptTab("batch");
      setBatchRunning(true);
      const scriptResult = await generateTrendingSingle(data);

      if (scriptResult) {
        setTrendingScriptData(scriptResult);
        refreshTrendingHistory();
        setAffiliateVideoFormConfig((prev) => {
          const next = withoutPromptSelection(prev);
          persistConfig(next);
          return next;
        });
      }
      setBatchRunning(false);
      return scriptResult;
    } catch (err: any) {
      console.error("[affiliate-video] submit error", err?.message);
      setBatchRunning(false);
      throw err;
    }
  };

  /** Persist config to IndexedDB */
  const persistConfig = (config: TrendingVideoFormConfig) => {
    scriptDB
      .set(CACHE_KEY.trendingInput, config)
      .catch((err) => console.warn("[affiliate-video] Failed to persist config", err));
  };

  const patchConfig = useCallback(
    (partial: Partial<TrendingVideoFormConfig>) => {
      setAffiliateVideoFormConfig((prev) => {
        const next = { ...prev, ...partial };
        persistConfig(next);
        return next;
      });

      if (partial.aspectRatio !== undefined) {
        syncSidebarPatchToCurrentScript({
          patch: { aspectRatio: partial.aspectRatio },
          setScriptData: setTrendingScriptData,
          selectedHistoryId: selectedTrendingHistoryId,
          setSceneHistory: setTrendingHistory,
          scriptDB,
          lastScriptCacheKey: CACHE_KEY.lastTrendingScript,
          historyCacheKey: CACHE_KEY.trendingHistory,
          logTag: "app",
        });
      }
    },
    [scriptDB, selectedTrendingHistoryId]
  );

  /** Wrapped setter that also persists to IndexedDB */
  const updateAffiliateVideoFormConfig = (config: TrendingVideoFormConfig) => {
    setAffiliateVideoFormConfig(config);
    persistConfig(config);
  };

  return (
    <AffiliateVideoContext.Provider
      value={{
        searchQuery,
        setSearchQuery,

        stopRef,
        SpeedModeOptions: SPEED_MODE_OPTIONS,
        DelayQueueOptions: DELAY_QUEUE_OPTIONS,
        ModeTabOptions: MODE_TAB_OPTIONS,
        MainTabOptions: MAIN_TAB_OPTIONS,
        VoiceModeOptions: VOICE_MODE_OPTIONS,
        VideoCountOptions: VIDEO_COUNT_OPTIONS,

        // script

        scriptTab,
        setScriptTab,
        batchList,
        setBatchList,

        batchRunning,
        batchGeneratingSceneIdsRef,
        addBatchGeneratingSceneId,
        removeBatchGeneratingSceneId,
        batchGeneratingVideoSceneIdsRef,
        addBatchGeneratingVideoSceneId,
        removeBatchGeneratingVideoSceneId,
        subscribeBatchState,
        reportSceneError,
        subscribeSceneError,
        getSceneErrors,
        reportSceneProgress,
        subscribeSceneProgress,

        // aliases used by AffiliateConfig
        videoConfig: affiliateVideoFormConfig,
        patchConfig,
        defaultVideoConfig: affiliateVideoFormConfig,
        affiliateVideoFormConfig,
        setAffiliateVideoFormConfig: updateAffiliateVideoFormConfig,

        sceneHistory: trendingHistory,
        selectedHistoryId: selectedTrendingHistoryId,
        selectHistoryItem: selectTrendingHistoryItem,
        clearSceneHistory: clearTrendingHistoryFn,
        refreshSceneHistory: refreshTrendingHistory,

        // story mode
        storyModeType,
        setStoryModeType: (mode: StoryModeTypeEnum) => {
          setStoryModeType(mode);
          // Persist storyModeType into lastScript
          scriptDB.get(CACHE_KEY.lastScript).then((cached) => {
            if (cached) {
              scriptDB
                .set(CACHE_KEY.lastScript, { ...cached, storyModeType: mode })
                .catch((e) => console.warn("[affiliate-video] Failed to persist storyModeType", e));
            }
          });
        },

        trendingModeType,
        setTrendingModeType: (mode: TrendingModeTypeEnum) => {
          setTrendingModeType(mode);
          // Persist trendingModeType into lastScript
          scriptDB.get(CACHE_KEY.lastTrendingScript).then((cached) => {
            if (cached) {
              scriptDB
                .set(CACHE_KEY.lastTrendingScript, { ...cached, trendingModeType: mode })
                .catch((e) =>
                  console.warn("[affiliate-video] Failed to persist trendingModeType", e)
                );
            }
          });
        },

        // pending prompt
        pendingPrompt,
        setPendingPrompt,
        handleSubmit,
        trendingScriptData,
        setTrendingScriptData,
        scriptData: trendingScriptData,

        // sidebar
        openSidebar: props.openSidebar || (() => {}),
      }}
    >
      {props.children}
    </AffiliateVideoContext.Provider>
  );
}

export const useAffiliateVideoContext = () => useContext(AffiliateVideoContext);
