import { t } from "../../../../helpers/functions/string";
import { SubscriptionPlanEnum } from "../../../../libs/dal/customer";
import { SettingResource } from "../../../../libs/shared/interfaces/settingResource";

const Type = SettingResource.Type;
export default {
  slug: "package",
  name: t("Cấu hình gói đăng ký"),
  settings: [
    // Unlimited
    {
      key: `pk-${SubscriptionPlanEnum.UNLIMITED}-video-limit`,
      name: t("Unlimited - Giới hạn video (-1 = không giới hạn)"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: -1,
    },
    {
      key: `pk-${SubscriptionPlanEnum.UNLIMITED}-image-limit`,
      name: t("Unlimited - Giới hạn ảnh (-1 = không giới hạn)"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: -1,
    },
    {
      key: `pk-${SubscriptionPlanEnum.UNLIMITED}-request-limit`,
      name: t("Unlimited - Giới hạn generation text (-1 = không giới hạn)"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: -1,
    },
    {
      key: `pk-${SubscriptionPlanEnum.UNLIMITED}-image-stream-count`,
      name: t("Unlimited - Số luồng ảnh đồng thời (-1 = không giới hạn)"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: -1,
    },
    {
      key: `pk-${SubscriptionPlanEnum.UNLIMITED}-video-stream-count`,
      name: t("Unlimited - Số luồng video đồng thời (-1 = không giới hạn)"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: -1,
    },
    {
      key: `pk-${SubscriptionPlanEnum.UNLIMITED}-price`,
      name: t("Unlimited - Giá (VNĐ)"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 1000000,
    },
    // Professional
    {
      key: `pk-${SubscriptionPlanEnum.PROFESSIONAL}-video-limit`,
      name: t("Professional - Giới hạn video"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 800,
    },
    {
      key: `pk-${SubscriptionPlanEnum.PROFESSIONAL}-image-limit`,
      name: t("Professional - Giới hạn ảnh"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 1200,
    },
    {
      key: `pk-${SubscriptionPlanEnum.PROFESSIONAL}-request-limit`,
      name: t("Professional - Giới hạn generation text"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 50,
    },
    {
      key: `pk-${SubscriptionPlanEnum.PROFESSIONAL}-image-stream-count`,
      name: t("Professional - Số luồng ảnh đồng thời"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 8,
    },
    {
      key: `pk-${SubscriptionPlanEnum.PROFESSIONAL}-video-stream-count`,
      name: t("Professional - Số luồng video đồng thời"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 10,
    },
    {
      key: `pk-${SubscriptionPlanEnum.PROFESSIONAL}-price`,
      name: t("Professional - Giá (VNĐ)"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 500000,
    },
    // Standard
    {
      key: `pk-${SubscriptionPlanEnum.STANDARD}-video-limit`,
      name: t("Standard - Giới hạn video"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 300,
    },
    {
      key: `pk-${SubscriptionPlanEnum.STANDARD}-image-limit`,
      name: t("Standard - Giới hạn ảnh"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 500,
    },
    {
      key: `pk-${SubscriptionPlanEnum.STANDARD}-request-limit`,
      name: t("Standard - Giới hạn generation text"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 50,
    },
    {
      key: `pk-${SubscriptionPlanEnum.STANDARD}-image-stream-count`,
      name: t("Standard - Số luồng ảnh đồng thời"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 5,
    },
    {
      key: `pk-${SubscriptionPlanEnum.STANDARD}-video-stream-count`,
      name: t("Standard - Số luồng video đồng thời"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 6,
    },
    {
      key: `pk-${SubscriptionPlanEnum.STANDARD}-price`,
      name: t("Standard - Giá (VNĐ)"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 200000,
    },
    // Basic
    {
      key: `pk-${SubscriptionPlanEnum.BASIC}-video-limit`,
      name: t("Basic - Giới hạn video"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 100,
    },
    {
      key: `pk-${SubscriptionPlanEnum.BASIC}-image-limit`,
      name: t("Basic - Giới hạn ảnh"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 300,
    },
    {
      key: `pk-${SubscriptionPlanEnum.BASIC}-request-limit`,
      name: t("Basic - Giới hạn generation text"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 20,
    },
    {
      key: `pk-${SubscriptionPlanEnum.BASIC}-image-stream-count`,
      name: t("Basic - Số luồng ảnh đồng thời"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 3,
    },
    {
      key: `pk-${SubscriptionPlanEnum.BASIC}-video-stream-count`,
      name: t("Basic - Số luồng video đồng thời"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 5,
    },
    {
      key: `pk-${SubscriptionPlanEnum.BASIC}-price`,
      name: t("Basic - Giá (VNĐ)"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 100000,
    },
    // Trial
    {
      key: `pk-${SubscriptionPlanEnum.TRIAL}-video-limit`,
      name: t("Trial - Giới hạn video"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 20,
    },
    {
      key: `pk-${SubscriptionPlanEnum.TRIAL}-image-limit`,
      name: t("Trial - Giới hạn ảnh"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 50,
    },
    {
      key: `pk-${SubscriptionPlanEnum.TRIAL}-request-limit`,
      name: t("Trial - Giới hạn generation text"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 10,
    },
    {
      key: `pk-${SubscriptionPlanEnum.TRIAL}-image-stream-count`,
      name: t("Trial - Số luồng ảnh đồng thời"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 2,
    },
    {
      key: `pk-${SubscriptionPlanEnum.TRIAL}-video-stream-count`,
      name: t("Trial - Số luồng video đồng thời"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 3,
    },
    {
      key: `pk-${SubscriptionPlanEnum.TRIAL}-price`,
      name: t("Trial - Giá (VNĐ)"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 0,
    },
    // Free
    {
      key: `pk-${SubscriptionPlanEnum.FREE}-video-limit`,
      name: t("Free - Giới hạn video"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 5,
    },
    {
      key: `pk-${SubscriptionPlanEnum.FREE}-image-limit`,
      name: t("Free - Giới hạn ảnh"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 10,
    },
    {
      key: `pk-${SubscriptionPlanEnum.FREE}-request-limit`,
      name: t("Free - Giới hạn generation text"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 5,
    },
    {
      key: `pk-${SubscriptionPlanEnum.FREE}-image-stream-count`,
      name: t("Free - Số luồng ảnh đồng thời"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 1,
    },
    {
      key: `pk-${SubscriptionPlanEnum.FREE}-video-stream-count`,
      name: t("Free - Số luồng video đồng thời"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 1,
    },
    {
      key: `pk-${SubscriptionPlanEnum.FREE}-price`,
      name: t("Free - Giá (VNĐ)"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 0,
    },
  ],
} as SettingResource.ConfigSchema;
