import { t } from "../../../../helpers/functions/string";
import { SettingResource } from "../../../../libs/shared/interfaces/settingResource";

const Type = SettingResource.Type;
export default {
  slug: "package",
  name: t("Cấu hình gói đăng ký"),
  settings: [
    // Unlimited
    {
      key: "pk-unlimited-video-limit",
      name: t("Unlimited - Giới hạn video (-1 = không giới hạn)"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: -1,
    },
    {
      key: "pk-unlimited-image-limit",
      name: t("Unlimited - Giới hạn ảnh (-1 = không giới hạn)"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: -1,
    },
    {
      key: "pk-unlimited-image-stream-count",
      name: t("Unlimited - Số luồng ảnh đồng thời (-1 = không giới hạn)"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: -1,
    },
    {
      key: "pk-unlimited-video-stream-count",
      name: t("Unlimited - Số luồng video đồng thời (-1 = không giới hạn)"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: -1,
    },
    {
      key: "pk-unlimited-price",
      name: t("Unlimited - Giá (VNĐ)"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 1000000,
    },
    // Professional
    {
      key: "pk-professional-video-limit",
      name: t("Professional - Giới hạn video"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 800,
    },
    {
      key: "pk-professional-image-limit",
      name: t("Professional - Giới hạn ảnh"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 1200,
    },
    {
      key: "pk-professional-image-stream-count",
      name: t("Professional - Số luồng ảnh đồng thời"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 8,
    },
    {
      key: "pk-professional-video-stream-count",
      name: t("Professional - Số luồng video đồng thời"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 10,
    },
    {
      key: "pk-professional-price",
      name: t("Professional - Giá (VNĐ)"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 500000,
    },
    // Standard
    {
      key: "pk-standard-video-limit",
      name: t("Standard - Giới hạn video"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 300,
    },
    {
      key: "pk-standard-image-limit",
      name: t("Standard - Giới hạn ảnh"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 500,
    },
    {
      key: "pk-standard-image-stream-count",
      name: t("Standard - Số luồng ảnh đồng thời"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 5,
    },
    {
      key: "pk-standard-video-stream-count",
      name: t("Standard - Số luồng video đồng thời"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 6,
    },
    {
      key: "pk-standard-price",
      name: t("Standard - Giá (VNĐ)"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 200000,
    },
    // Basic
    {
      key: "pk-basic-video-limit",
      name: t("Basic - Giới hạn video"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 100,
    },
    {
      key: "pk-basic-image-limit",
      name: t("Basic - Giới hạn ảnh"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 300,
    },
    {
      key: "pk-basic-image-stream-count",
      name: t("Basic - Số luồng ảnh đồng thời"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 3,
    },
    {
      key: "pk-basic-video-stream-count",
      name: t("Basic - Số luồng video đồng thời"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 5,
    },
    {
      key: "pk-basic-price",
      name: t("Basic - Giá (VNĐ)"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 100000,
    },
    // Trial
    {
      key: "pk-trial-video-limit",
      name: t("Trial - Giới hạn video"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 20,
    },
    {
      key: "pk-trial-image-limit",
      name: t("Trial - Giới hạn ảnh"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 50,
    },
    {
      key: "pk-trial-image-stream-count",
      name: t("Trial - Số luồng ảnh đồng thời"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 2,
    },
    {
      key: "pk-trial-video-stream-count",
      name: t("Trial - Số luồng video đồng thời"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 3,
    },
    {
      key: "pk-trial-price",
      name: t("Trial - Giá (VNĐ)"),
      type: Type.number,
      isPrivate: false,
      isSecret: false,
      isActive: true,
      value: 0,
    },
  ],
} as SettingResource.ConfigSchema;
