import { createContext, useCallback, useContext, useEffect, useRef, useState } from "react";
import { useOptionsTranslation } from "../../../../../lib/hooks/useOptionsTranslate";
import { useAuth } from "../../../../../lib/providers/auth-provider";
import { useGlobalContext } from "../../../../../lib/providers/global-provider";
import { useToast } from "../../../../../lib/providers/toast-provider";
import {
  AffiliateVideoFormConfig,
  CACHE_KEY,
  DB_NAME,
  SceneHistoryItem,
  ScriptData,
  STORE_NAME,
  StoryModeTypeEnum,
  StoryboardImageStatus,
} from "../../constants";
import { GenerateSceneFromTextParams } from "../../copy-video/hook/useCopyVideoApi";
import { useAffiliateVideoApi } from "../../hook/useAffiliateVideoApi";
import { useIndexedDB } from "../../hook/useIndexedDB";
import {
  replaceStoryboardImageScenes,
} from "../utils/storyboardScriptUtils";
import {
  SceneErrorKind,
  SceneErrors,
  useSceneErrorBroadcast,
} from "../../hook/useSceneErrorBroadcast";
import {
  SceneProgress,
  SceneProgressKind,
  useSceneProgressBroadcast,
} from "../../hook/useSceneProgressBroadcast";

/** Key used to persist the last generated script in IndexedDB */

export const AffiliateVideoContext = createContext<
  Partial<{
    modeTab: ModeTab;
    setModeTab: (modeTab: ModeTab) => void;
    speed: SpeedMode | string;
    setSpeed: (speed: SpeedMode | string) => void;
    delayQueue: DelayQueue;
    setDelayQueue: (delayQueue: DelayQueue) => void;
    searchQuery: string;
    setSearchQuery: (searchQuery: string) => void;
    voiceMode: VoiceMode;
    setVoiceMode: (voiceMode: VoiceMode) => void;
    videoConfig: AffiliateVideoFormConfig;
    setVideoConfig: (videoConfig: AffiliateVideoFormConfig) => void;
    showAiModal: boolean;
    setShowAiModal: (showAiModal: boolean) => void;
    batchRunning: boolean;
    setBatchRunning: (batchRunning: boolean) => void;
    activeTab: MainTab;
    setActiveTab: (activeTab: MainTab) => void;

    zoomSrc: { src: string; type: "image" | "video" } | null;
    setZoomSrc: (zoomSrc: { src: string; type: "image" | "video" } | null) => void;
    stopRef: React.MutableRefObject<boolean>;
    SpeedModeOptions?: { label: string; value: SpeedMode | string }[];
    DelayQueueOptions?: { label: string; value: DelayQueue | string }[];
    ModeTabOptions?: { label: string; value: ModeTab | string }[];
    MainTabOptions?: { label: string; value: MainTab | string }[];
    VoiceModeOptions?: { label: string; value: VoiceMode | string }[];
    VideoCountOptions?: { label: string; value: number }[];
    totalCount: number;
    doneCount: number;
    patchConfig: (p: Partial<AffiliateVideoFormConfig>) => void;

    useMock: boolean;
    genCount: number;
    histCount: number;

    /** Convenience getter – returns current form values as AffiliateFormConfig */
    affiliateFormConfig: AffiliateVideoFormConfig;
    // ── Script data ──
    scriptData: ScriptData | null;
    setScriptData: (data: ScriptData | null) => void;
    scriptTab: "script" | "batch";
    setScriptTab: (tab: "script" | "batch") => void;
    batchList: string[];
    setBatchList: (list: string[]) => void;
    handleSubmit: (data: AffiliateVideoFormConfig, promptText?: string) => void;
    generateSceneFromText: (params: GenerateSceneFromTextParams) => Promise<ScriptData | undefined>;
    affiliateVideoFormConfig: AffiliateVideoFormConfig;
    setAffiliateVideoFormConfig: (videoConfig: AffiliateVideoFormConfig) => void;
    defaultVideoConfig: AffiliateVideoFormConfig;
    /** Ref holding scene IDs currently being generated by batch process */
    batchGeneratingSceneIdsRef: React.MutableRefObject<Set<string>>;
    /** Add a scene ID to the batch-generating set */
    addBatchGeneratingSceneId: (id: string) => void;
    /** Remove a scene ID from the batch-generating set */
    removeBatchGeneratingSceneId: (id: string) => void;
    /** Ref holding scene IDs currently generating video by batch process */
    batchGeneratingVideoSceneIdsRef: React.MutableRefObject<Set<string>>;
    /** Add a scene ID to the batch-video-generating set */
    addBatchGeneratingVideoSceneId: (id: string) => void;
    /** Remove a scene ID from the batch-video-generating set */
    removeBatchGeneratingVideoSceneId: (id: string) => void;
    /** Subscribe to batch generating state changes for a specific scene */
    subscribeBatchState: (
      sceneId: string,
      callback: (
        generating: boolean,
        generatingVideo: boolean,
        generatingExtendVideo: boolean
      ) => void
    ) => () => void;
    /** Báo lỗi inline cho 1 scene (dùng cho batch/single generation) */
    reportSceneError: (sceneId: string, kind: SceneErrorKind, message: string | null) => void;
    /** Subscribe state lỗi inline cho 1 scene */
    subscribeSceneError: (sceneId: string, callback: (errors: SceneErrors) => void) => () => void;
    getSceneErrors: (sceneId: string) => SceneErrors;
    reportSceneProgress: (
      sceneId: string,
      kind: SceneProgressKind,
      progress: number | null
    ) => void;
    subscribeSceneProgress: (
      sceneId: string,
      callback: (progress: SceneProgress) => void
    ) => () => void;

    // ── Scene history ──
    /** Full history list (newest first) */
    sceneHistory: SceneHistoryItem[];
    /** Currently selected history item ID (null = latest / no history) */
    selectedHistoryId: string | null;
    /** Select a history item by ID and apply its data */
    selectHistoryItem: (id: string) => void;
    /** Clear all scene generation history */
    clearSceneHistory: () => Promise<void>;
    /** Refresh history from IndexedDB */
    refreshSceneHistory: () => Promise<void>;

    storyModeType: StoryModeTypeEnum;
    setStoryModeType: (storyModeType: StoryModeTypeEnum) => void;

    /** Trạng thái phân tích từng ảnh storyboard (theo index upload) */
    storyboardImageStatuses: Record<number, StoryboardImageStatus>;
    /** Tiến độ phân tích storyboard: ảnh hiện tại / tổng */
    storyboardProgress: { current: number; total: number } | null;
    /** Tạo lại phân cảnh cho một ảnh storyboard bị lỗi */
    retryStoryboardImage: (imageIndex: number) => Promise<void>;
  }>
>({});

export function AffiliateVideoProvider(props) {
  const {
    analyzeStoryboard,
    analyzeStoryboardImage,
    generateSceneFromText,
    getStoryboardHistory,
    clearStoryboardHistory: clearStoryboardHistoryApi,
  } = useAffiliateVideoApi();
  const { customer } = useAuth();
  const { setOpenCustomerLoginDialog } = useGlobalContext();
  const toast = useToast();
  const [searchQuery, setSearchQuery] = useState("");
  const stopRef = useRef(false);

  // ── IndexedDB – shared cache for AI results ──
  const scriptDB = useIndexedDB<any>(STORE_NAME.generateScene, DB_NAME.generateScene);

  // ── Script / Batch state ──
  const [scriptData, setScriptData] = useState<ScriptData | null>(null);
  const [scriptTab, setScriptTab] = useState<"script" | "batch">("script");
  const [batchList, setBatchList] = useState<string[]>(["Kịch bản 1"]);
  const [batchRunning, setBatchRunning] = useState(false);
  // ── Batch generating state: refs + per-scene subscriptions ──
  // Using refs instead of state to avoid re-rendering ALL context consumers
  // when a single scene's batch state changes.
  const batchGeneratingSceneIdsRef = useRef<Set<string>>(new Set());
  const batchGeneratingVideoSceneIdsRef = useRef<Set<string>>(new Set());
  const batchSubscribersRef = useRef<
    Map<
      string,
      (generating: boolean, generatingVideo: boolean, generatingExtendVideo: boolean) => void
    >
  >(new Map());

  // ── Per-scene inline error broadcast (batch generation failures) ──
  const { reportSceneError, subscribeSceneError, getSceneErrors } = useSceneErrorBroadcast();
  const { reportSceneProgress, subscribeSceneProgress } = useSceneProgressBroadcast();

  const [storyModeType, setStoryModeType] = useState<StoryModeTypeEnum>(
    StoryModeTypeEnum.image_to_video
  );

  const [storyboardImageStatuses, setStoryboardImageStatuses] = useState<
    Record<number, StoryboardImageStatus>
  >({});
  const [storyboardProgress, setStoryboardProgress] = useState<{
    current: number;
    total: number;
  } | null>(null);

  // ── Scene history state ──
  const [sceneHistory, setSceneHistory] = useState<SceneHistoryItem[]>([]);
  const [selectedHistoryId, setSelectedHistoryId] = useState<string | null>(null);

  /** Notify a scene's subscriber of its current batch state */
  const notifySubscriber = useCallback((sceneId: string) => {
    // Extract base scene ID (strip ::stitch suffix)
    const baseId = sceneId.replace(/::stitch$/, "");
    const cb = batchSubscribersRef.current.get(baseId);
    if (cb) {
      cb(
        batchGeneratingSceneIdsRef.current.has(baseId),
        batchGeneratingVideoSceneIdsRef.current.has(baseId),
        batchGeneratingVideoSceneIdsRef.current.has(baseId + "::stitch")
      );
    }
  }, []);

  /** Subscribe to batch state changes for a specific scene */
  const subscribeBatchState = useCallback(
    (
      sceneId: string,
      callback: (
        generating: boolean,
        generatingVideo: boolean,
        generatingExtendVideo: boolean
      ) => void
    ) => {
      batchSubscribersRef.current.set(sceneId, callback);
      // Immediately notify with current state
      callback(
        batchGeneratingSceneIdsRef.current.has(sceneId),
        batchGeneratingVideoSceneIdsRef.current.has(sceneId),
        batchGeneratingVideoSceneIdsRef.current.has(sceneId + "::stitch")
      );
      return () => {
        batchSubscribersRef.current.delete(sceneId);
      };
    },
    []
  );

  const addBatchGeneratingSceneId = useCallback(
    (id: string) => {
      batchGeneratingSceneIdsRef.current.add(id);
      notifySubscriber(id);
    },
    [notifySubscriber]
  );

  const removeBatchGeneratingSceneId = useCallback(
    (id: string) => {
      batchGeneratingSceneIdsRef.current.delete(id);
      notifySubscriber(id);
    },
    [notifySubscriber]
  );

  const addBatchGeneratingVideoSceneId = useCallback(
    (id: string) => {
      batchGeneratingVideoSceneIdsRef.current.add(id);
      notifySubscriber(id);
    },
    [notifySubscriber]
  );

  const removeBatchGeneratingVideoSceneId = useCallback(
    (id: string) => {
      batchGeneratingVideoSceneIdsRef.current.delete(id);
      notifySubscriber(id);
    },
    [notifySubscriber]
  );

  const {
    DEFAULT_VIDEO_CONFIG,
    SPEED_MODE_OPTIONS,
    DELAY_QUEUE_OPTIONS,
    MODE_TAB_OPTIONS,
    MAIN_TAB_OPTIONS,
    VOICE_MODE_OPTIONS,
    VIDEO_COUNT_OPTIONS,
  } = useOptionsTranslation();
  const [affiliateVideoFormConfig, setAffiliateVideoFormConfig] =
    useState<AffiliateVideoFormConfig>(DEFAULT_VIDEO_CONFIG);

  // ── On mount: restore last cached script + config from IndexedDB ──
  useEffect(() => {
    if (customer?._id) {
      getSceneList();
      restoreConfigFromDB();
      refreshSceneHistory();
    }
  }, [customer?._id]);

  /** Refresh history list from IndexedDB */
  const refreshSceneHistory = useCallback(async () => {
    try {
      const history = await getStoryboardHistory();
      setSceneHistory(history);
    } catch (err) {
      console.warn("[storyboard] Failed to load scene history", err);
    }
  }, [getStoryboardHistory]);

  /** Select a history item by ID and apply its data to scriptData */
  const selectHistoryItem = useCallback(
    (id: string) => {
      const item = sceneHistory.find((h) => h.id === id);
      if (item) {
        setSelectedHistoryId(id);
        setScriptData(item.data);
        // Also update lastScript so it persists across page reloads
        scriptDB.set(CACHE_KEY.lastStoryboardScript, item.data).catch(() => {});
      }
    },
    [sceneHistory, scriptDB]
  );

  /** Clear all history */
  const clearSceneHistoryFn = useCallback(async () => {
    await clearStoryboardHistoryApi();
    setSceneHistory([]);
    setSelectedHistoryId(null);
  }, [clearStoryboardHistoryApi]);

  const getSceneList = async () => {
    try {
      const cached = await scriptDB.get(CACHE_KEY.lastStoryboardScript);
      if (cached) {
        setScriptData(cached);
      }
    } catch (err) {
      console.warn("[affiliate-video] IndexedDB read error", err);
    }
  };

  /** Restore form config from IndexedDB; fall back to DEFAULT_VIDEO_CONFIG */

  const restoreConfigFromDB = async () => {
    try {
      const cachedConfig = await scriptDB.get(CACHE_KEY.storyboardInput);
      if (cachedConfig) {
        setAffiliateVideoFormConfig(cachedConfig);
      }
    } catch (err) {
      console.warn("[affiliate-video] Failed to restore config from IndexedDB", err);
    }
  };

  const handleSubmit = async (data: AffiliateVideoFormConfig, promptText?: string) => {
    if (!customer) {
      setOpenCustomerLoginDialog(true);
      return;
    }

    const uploadedIndices = (data.storyboardImage ?? [])
      .map((img, index) => (img?.imageBytes ? index : -1))
      .filter((index) => index >= 0);

    if (!uploadedIndices.length) {
      toast.error("Vui lòng upload ảnh storyboard trước khi tạo cảnh");
      return;
    }

    try {
      setScriptTab("script");
      setBatchRunning(true);
      setStoryboardImageStatuses({});
      setStoryboardProgress({ current: 0, total: uploadedIndices.length });
      setScriptData(null);
      setSelectedHistoryId(null);

      let completedCount = 0;

      const scriptResult = promptText
        ? await generateSceneFromText({ text: promptText, config: data })
        : await analyzeStoryboard(data, {
            onImageStatus: (index, status) => {
              setStoryboardImageStatuses((prev) => ({ ...prev, [index]: status }));
              if (status === "done" || status === "error") {
                completedCount += 1;
                setStoryboardProgress({
                  current: completedCount,
                  total: uploadedIndices.length,
                });
              }
            },
            onProgress: (partial) => {
              setScriptData(partial);
            },
          });

      if (scriptResult) {
        setScriptData(scriptResult);
        refreshSceneHistory();
      }
      setBatchRunning(false);
      setStoryboardProgress(null);
      return scriptResult;
    } catch (err: any) {
      console.error("[storyboard] submit error", err?.message);
      setBatchRunning(false);
      setStoryboardProgress(null);
      throw err;
    }
  };

  const retryStoryboardImage = useCallback(
    async (imageIndex: number) => {
      if (!customer) {
        setOpenCustomerLoginDialog(true);
        return;
      }

      const data = affiliateVideoFormConfig;
      const storyboardImage = data.storyboardImage?.[imageIndex];
      if (!storyboardImage?.imageBytes) {
        toast.error("Ảnh storyboard không hợp lệ");
        return;
      }

      const currentScript = scriptData;

      setStoryboardImageStatuses((prev) => ({ ...prev, [imageIndex]: "loading" }));

      try {
        if (!currentScript) {
          const partial = await analyzeStoryboardImage(data, storyboardImage, {
            sourceIndex: imageIndex,
            sceneNumberOffset: 0,
          });

          if (!partial) {
            setStoryboardImageStatuses((prev) => ({ ...prev, [imageIndex]: "error" }));
            return;
          }

          setScriptData(partial);
          setStoryboardImageStatuses((prev) => ({ ...prev, [imageIndex]: "done" }));
          scriptDB
            .set(CACHE_KEY.lastStoryboardScript, partial)
            .catch((e) => console.warn("[storyboard] Failed to persist script", e));
          return;
        }

        const scenesBefore = currentScript.scenes.filter(
          (scene) => (scene.storyboardSourceIndex ?? 0) < imageIndex
        );
        const sceneNumberOffset = scenesBefore.length;

        const partial = await analyzeStoryboardImage(data, storyboardImage, {
          sourceIndex: imageIndex,
          sceneNumberOffset,
        });

        if (!partial) {
          setStoryboardImageStatuses((prev) => ({ ...prev, [imageIndex]: "error" }));
          return;
        }

        const nextScript = replaceStoryboardImageScenes(
          currentScript,
          imageIndex,
          partial.scenes
        );

        setScriptData(nextScript);
        setStoryboardImageStatuses((prev) => ({ ...prev, [imageIndex]: "done" }));

        scriptDB
          .set(CACHE_KEY.lastStoryboardScript, nextScript)
          .catch((e) => console.warn("[storyboard] Failed to persist script", e));
      } catch (err: any) {
        console.error("[storyboard] retry error", err?.message);
        setStoryboardImageStatuses((prev) => ({ ...prev, [imageIndex]: "error" }));
      }
    },
    [
      affiliateVideoFormConfig,
      analyzeStoryboardImage,
      customer,
      scriptData,
      scriptDB,
      setOpenCustomerLoginDialog,
      toast,
    ]
  );

  /** Persist config to IndexedDB */
  const persistConfig = (config: AffiliateVideoFormConfig) => {
    scriptDB
      .set(CACHE_KEY.storyboardInput, config)
      .catch((err) => console.warn("[storyboard] Failed to persist config", err));
  };

  const patchConfig = (partial: Partial<AffiliateVideoFormConfig>) => {
    setAffiliateVideoFormConfig((prev) => {
      const next = { ...prev, ...partial };

      persistConfig(next);
      return next;
    });
  };

  /** Wrapped setter that also persists to IndexedDB */
  const updateAffiliateVideoFormConfig = (config: AffiliateVideoFormConfig) => {
    setAffiliateVideoFormConfig(config);
    persistConfig(config);
  };

  return (
    <AffiliateVideoContext.Provider
      value={{
        searchQuery,
        setSearchQuery,

        stopRef,
        SpeedModeOptions: SPEED_MODE_OPTIONS,
        DelayQueueOptions: DELAY_QUEUE_OPTIONS,
        ModeTabOptions: MODE_TAB_OPTIONS,
        MainTabOptions: MAIN_TAB_OPTIONS,
        VoiceModeOptions: VOICE_MODE_OPTIONS,
        VideoCountOptions: VIDEO_COUNT_OPTIONS,

        // script
        scriptData,
        setScriptData,
        scriptTab,
        setScriptTab,
        batchList,
        setBatchList,
        handleSubmit,
        generateSceneFromText,
        affiliateVideoFormConfig,
        setAffiliateVideoFormConfig: updateAffiliateVideoFormConfig,
        defaultVideoConfig: affiliateVideoFormConfig,
        batchRunning,
        batchGeneratingSceneIdsRef,
        addBatchGeneratingSceneId,
        removeBatchGeneratingSceneId,
        batchGeneratingVideoSceneIdsRef,
        addBatchGeneratingVideoSceneId,
        removeBatchGeneratingVideoSceneId,
        subscribeBatchState,
        reportSceneError,
        subscribeSceneError,
        getSceneErrors,
        reportSceneProgress,
        subscribeSceneProgress,

        // aliases used by AffiliateConfig
        videoConfig: affiliateVideoFormConfig,
        patchConfig,

        // scene history
        sceneHistory,
        selectedHistoryId,
        selectHistoryItem,
        clearSceneHistory: clearSceneHistoryFn,
        refreshSceneHistory,

        // story mode
        storyModeType,
        setStoryModeType: (mode: StoryModeTypeEnum) => {
          setStoryModeType(mode);
          // Persist storyModeType into lastScript
          scriptDB.get(CACHE_KEY.lastStoryboardScript).then((cached) => {
            if (cached) {
              scriptDB
                .set(CACHE_KEY.lastStoryboardScript, { ...cached, storyModeType: mode })
                .catch((e) => console.warn("[storyboard] Failed to persist storyModeType", e));
            }
          });
        },

        storyboardImageStatuses,
        storyboardProgress,
        retryStoryboardImage,
      }}
    >
      {props.children}
    </AffiliateVideoContext.Provider>
  );
}

export const useAffiliateVideoContext = () => useContext(AffiliateVideoContext);
