import { createContext, useCallback, useContext, useEffect, useRef, useState } from "react";
import { useOptionsTranslation } from "../../../../lib/hooks/useOptionsTranslate";
import { useAuth } from "../../../../lib/providers/auth-provider";
import { useGlobalContext } from "../../../../lib/providers/global-provider";
import {
  AffiliateVideoFormConfig,
  CACHE_KEY,
  DB_NAME,
  SceneHistoryItem,
  ScriptData,
  STORE_NAME,
  StoryModeTypeEnum,
} from "../constants";
import { GenerateSceneFromTextParams, useAffiliateVideoApi } from "../hook/useAffiliateVideoApi";
import { useIndexedDB } from "../hook/useIndexedDB";

/** Key used to persist the last generated script in IndexedDB */

export const AffiliateVideoContext = createContext<
  Partial<{
    modeTab: ModeTab;
    setModeTab: (modeTab: ModeTab) => void;
    speed: SpeedMode | string;
    setSpeed: (speed: SpeedMode | string) => void;
    delayQueue: DelayQueue;
    setDelayQueue: (delayQueue: DelayQueue) => void;
    searchQuery: string;
    setSearchQuery: (searchQuery: string) => void;
    voiceMode: VoiceMode;
    setVoiceMode: (voiceMode: VoiceMode) => void;
    videoConfig: AffiliateVideoFormConfig;
    setVideoConfig: (videoConfig: AffiliateVideoFormConfig) => void;
    showAiModal: boolean;
    setShowAiModal: (showAiModal: boolean) => void;
    batchRunning: boolean;
    setBatchRunning: (batchRunning: boolean) => void;
    activeTab: MainTab;
    setActiveTab: (activeTab: MainTab) => void;

    zoomSrc: { src: string; type: "image" | "video" } | null;
    setZoomSrc: (zoomSrc: { src: string; type: "image" | "video" } | null) => void;
    stopRef: React.MutableRefObject<boolean>;
    SpeedModeOptions?: { label: string; value: SpeedMode | string }[];
    DelayQueueOptions?: { label: string; value: DelayQueue | string }[];
    ModeTabOptions?: { label: string; value: ModeTab | string }[];
    MainTabOptions?: { label: string; value: MainTab | string }[];
    VoiceModeOptions?: { label: string; value: VoiceMode | string }[];
    VideoCountOptions?: { label: string; value: number }[];
    totalCount: number;
    doneCount: number;
    patchConfig: (p: Partial<AffiliateVideoFormConfig>) => void;

    useMock: boolean;
    genCount: number;
    histCount: number;

    /** Convenience getter – returns current form values as AffiliateFormConfig */
    affiliateFormConfig: AffiliateVideoFormConfig;
    // ── Script data ──
    scriptData: ScriptData | null;
    setScriptData: (data: ScriptData | null) => void;
    scriptTab: "script" | "batch";
    setScriptTab: (tab: "script" | "batch") => void;
    batchList: string[];
    setBatchList: (list: string[]) => void;
    handleSubmit: (data: AffiliateVideoFormConfig, promptText?: string) => void;
    generateSceneFromText: (params: GenerateSceneFromTextParams) => Promise<ScriptData | undefined>;
    affiliateVideoFormConfig: AffiliateVideoFormConfig;
    setAffiliateVideoFormConfig: (videoConfig: AffiliateVideoFormConfig) => void;
    defaultVideoConfig: AffiliateVideoFormConfig;
    /** Set of scene IDs currently being generated by batch process */
    batchGeneratingSceneIds: Set<string>;
    /** Add a scene ID to the batch-generating set */
    addBatchGeneratingSceneId: (id: string) => void;
    /** Remove a scene ID from the batch-generating set */
    removeBatchGeneratingSceneId: (id: string) => void;
    /** Set of scene IDs currently generating video by batch process */
    batchGeneratingVideoSceneIds: Set<string>;
    /** Add a scene ID to the batch-video-generating set */
    addBatchGeneratingVideoSceneId: (id: string) => void;
    /** Remove a scene ID from the batch-video-generating set */
    removeBatchGeneratingVideoSceneId: (id: string) => void;

    // ── Scene history ──
    /** Full history list (newest first) */
    sceneHistory: SceneHistoryItem[];
    /** Currently selected history item ID (null = latest / no history) */
    selectedHistoryId: string | null;
    /** Select a history item by ID and apply its data */
    selectHistoryItem: (id: string) => void;
    /** Clear all scene generation history */
    clearSceneHistory: () => Promise<void>;
    /** Refresh history from IndexedDB */
    refreshSceneHistory: () => Promise<void>;

    storyModeType: StoryModeTypeEnum;
    setStoryModeType: (storyModeType: StoryModeTypeEnum) => void;
  }>
>({});

export function AffiliateVideoProvider(props) {
  const {
    generateScene,
    generateSceneFromText,
    getSceneHistory,
    clearSceneHistory: clearSceneHistoryApi,
  } = useAffiliateVideoApi();
  const { customer } = useAuth();
  const { setOpenCustomerLoginDialog } = useGlobalContext();
  const [searchQuery, setSearchQuery] = useState("");
  const stopRef = useRef(false);

  // ── IndexedDB – shared cache for AI results ──
  const scriptDB = useIndexedDB<any>(STORE_NAME.generateScene, DB_NAME.generateScene);

  // ── Script / Batch state ──
  const [scriptData, setScriptData] = useState<ScriptData | null>(null);
  const [scriptTab, setScriptTab] = useState<"script" | "batch">("script");
  const [batchList, setBatchList] = useState<string[]>(["Kịch bản 1"]);
  const [batchRunning, setBatchRunning] = useState(false);
  const [batchGeneratingSceneIds, setBatchGeneratingSceneIds] = useState<Set<string>>(new Set());
  const [batchGeneratingVideoSceneIds, setBatchGeneratingVideoSceneIds] = useState<Set<string>>(
    new Set()
  );

  const [storyModeType, setStoryModeType] = useState<StoryModeTypeEnum>(
    StoryModeTypeEnum.image_to_video
  );

  // ── Scene history state ──
  const [sceneHistory, setSceneHistory] = useState<SceneHistoryItem[]>([]);
  const [selectedHistoryId, setSelectedHistoryId] = useState<string | null>(null);

  const addBatchGeneratingSceneId = useCallback((id: string) => {
    setBatchGeneratingSceneIds((prev) => new Set(prev).add(id));
  }, []);

  const removeBatchGeneratingSceneId = useCallback((id: string) => {
    setBatchGeneratingSceneIds((prev) => {
      const next = new Set(prev);
      next.delete(id);
      return next;
    });
  }, []);

  const addBatchGeneratingVideoSceneId = useCallback((id: string) => {
    setBatchGeneratingVideoSceneIds((prev) => new Set(prev).add(id));
  }, []);

  const removeBatchGeneratingVideoSceneId = useCallback((id: string) => {
    setBatchGeneratingVideoSceneIds((prev) => {
      const next = new Set(prev);
      next.delete(id);
      return next;
    });
  }, []);

  const {
    DEFAULT_VIDEO_CONFIG,
    SPEED_MODE_OPTIONS,
    DELAY_QUEUE_OPTIONS,
    MODE_TAB_OPTIONS,
    MAIN_TAB_OPTIONS,
    VOICE_MODE_OPTIONS,
    VIDEO_COUNT_OPTIONS,
  } = useOptionsTranslation();
  const [affiliateVideoFormConfig, setAffiliateVideoFormConfig] =
    useState<AffiliateVideoFormConfig>(DEFAULT_VIDEO_CONFIG);

  // ── On mount: restore last cached script + config from IndexedDB ──
  useEffect(() => {
    getSceneList();
    restoreConfigFromDB();
    refreshSceneHistory();
  }, []);

  /** Refresh history list from IndexedDB */
  const refreshSceneHistory = useCallback(async () => {
    try {
      const history = await getSceneHistory();
      setSceneHistory(history);
    } catch (err) {
      console.warn("[affiliate-video] Failed to load scene history", err);
    }
  }, [getSceneHistory]);

  /** Select a history item by ID and apply its data to scriptData */
  const selectHistoryItem = useCallback(
    (id: string) => {
      const item = sceneHistory.find((h) => h.id === id);
      if (item) {
        setSelectedHistoryId(id);
        setScriptData(item.data);
        // Also update lastScript so it persists across page reloads
        scriptDB.set(CACHE_KEY.lastScript, item.data).catch(() => {});
      }
    },
    [sceneHistory, scriptDB]
  );

  /** Clear all history */
  const clearSceneHistoryFn = useCallback(async () => {
    await clearSceneHistoryApi();
    setSceneHistory([]);
    setSelectedHistoryId(null);
  }, [clearSceneHistoryApi]);

  const getSceneList = async () => {
    try {
      const cached = await scriptDB.get(CACHE_KEY.lastScript);
      if (cached) {
        setScriptData(cached);
      }
    } catch (err) {
      console.warn("[affiliate-video] IndexedDB read error", err);
    }
  };

  /** Restore form config from IndexedDB; fall back to DEFAULT_VIDEO_CONFIG */

  const restoreConfigFromDB = async () => {
    try {
      const cachedConfig = await scriptDB.get(CACHE_KEY.generateInput);
      if (cachedConfig) {
        setAffiliateVideoFormConfig(cachedConfig);
      }
    } catch (err) {
      console.warn("[affiliate-video] Failed to restore config from IndexedDB", err);
    }
  };

  const handleSubmit = async (data: AffiliateVideoFormConfig, promptText?: string) => {
    if (!customer) {
      setOpenCustomerLoginDialog(true);
      return;
    }
    try {
      setScriptTab("script");
      setBatchRunning(true);
      const scriptResult = promptText
        ? await generateSceneFromText({ text: promptText, config: data })
        : await generateScene(data);

      if (scriptResult) {
        setScriptData(scriptResult);
        // Refresh history to include the new entry
        refreshSceneHistory();
      }
      setBatchRunning(false);
      return scriptResult;
    } catch (err: any) {
      console.error("[affiliate-video] submit error", err?.message);
      setBatchRunning(false);
      throw err;
    }
  };

  /** Persist config to IndexedDB */
  const persistConfig = (config: AffiliateVideoFormConfig) => {
    scriptDB
      .set(CACHE_KEY.generateInput, config)
      .catch((err) => console.warn("[affiliate-video] Failed to persist config", err));
  };

  const patchConfig = (partial: Partial<AffiliateVideoFormConfig>) => {
    setAffiliateVideoFormConfig((prev) => {
      const next = { ...prev, ...partial };

      persistConfig(next);
      return next;
    });
  };

  /** Wrapped setter that also persists to IndexedDB */
  const updateAffiliateVideoFormConfig = (config: AffiliateVideoFormConfig) => {
    setAffiliateVideoFormConfig(config);
    persistConfig(config);
  };

  return (
    <AffiliateVideoContext.Provider
      value={{
        searchQuery,
        setSearchQuery,

        stopRef,
        SpeedModeOptions: SPEED_MODE_OPTIONS,
        DelayQueueOptions: DELAY_QUEUE_OPTIONS,
        ModeTabOptions: MODE_TAB_OPTIONS,
        MainTabOptions: MAIN_TAB_OPTIONS,
        VoiceModeOptions: VOICE_MODE_OPTIONS,
        VideoCountOptions: VIDEO_COUNT_OPTIONS,

        // script
        scriptData,
        setScriptData,
        scriptTab,
        setScriptTab,
        batchList,
        setBatchList,
        handleSubmit,
        generateSceneFromText,
        affiliateVideoFormConfig,
        setAffiliateVideoFormConfig: updateAffiliateVideoFormConfig,
        defaultVideoConfig: affiliateVideoFormConfig,
        batchRunning,
        batchGeneratingSceneIds,
        addBatchGeneratingSceneId,
        removeBatchGeneratingSceneId,
        batchGeneratingVideoSceneIds,
        addBatchGeneratingVideoSceneId,
        removeBatchGeneratingVideoSceneId,

        // aliases used by AffiliateConfig
        videoConfig: affiliateVideoFormConfig,
        patchConfig,

        // scene history
        sceneHistory,
        selectedHistoryId,
        selectHistoryItem,
        clearSceneHistory: clearSceneHistoryFn,
        refreshSceneHistory,

        // story mode
        storyModeType,
        setStoryModeType,
      }}
    >
      {props.children}
    </AffiliateVideoContext.Provider>
  );
}

export const useAffiliateVideoContext = () => useContext(AffiliateVideoContext);
