export const SCOPES = {
  //ANALYTIC
  VIEW_ANALYTIC: "AN-1-1",
  // USER
  VIEW_USER: "QT-1-1",
  CREATE_USER: "QT-1-2",
  EDIT_USER: "QT-1-3",
  DELETE_USER: "QT-1-4",
  BANK_USER: "QT-1-5",
  LIMIT_USER: "QT-1-6",
  // MEMBER
  VIEW_MEMBER: "QT-2-1",
  CREATE_MEMBER: "QT-2-2",
  EDIT_MEMBER: "QT-2-3",
  DELETE_MEMBER: "QT-2-4",
  // CUSTOMER
  VIEW_CUSTOMER: "QT-3-1",
  CREATE_CUSTOMER: "QT-3-2",
  EDIT_CUSTOMER: "QT-3-3",
  DELETE_CUSTOMER: "QT-3-4",
  EXCEL_CUSTOMER: "QT-3-5",
  // PRODUCT
  VIEW_PRODUCT: "QT-4-1",
  CREATE_PRODUCT: "QT-4-2",
  EDIT_PRODUCT: "QT-4-3",
  DELETE_PRODUCT: "QT-4-4",
  // ORDER
  VIEW_ORDER: "QT-20-1",
  CREATE_ORDER: "QT-20-2",
  EDIT_ORDER: "QT-20-3",
  DELETE_ORDER: "QT-20-4",
  CREATE_SHIPPING_ORDER: "QT-20-5",

  VIEW_SHOP_VIDEO: "QT-5-1",

  EDIT_SHOP_VIDEO: "QT-5-2",
  DELETE_SHOP_VIDEO: "QT-5-3",

  // CATEGORY
  // VIEW_CATEGORY: "QT-5-1",
  // CREATE_CATEGORY: "QT-5-2",
  // EDIT_CATEGORY: "QT-5-3",
  // DELETE_CATEGORY: "QT-5-4",
  // BANNER
  VIEW_BANNER: "QT-6-1",
  CREATE_BANNER: "QT-6-2",
  EDIT_BANNER: "QT-6-3",
  DELETE_BANNER: "QT-6-4",
  // POPUP_NOTIFY
  VIEW_POPUP_NOTIFY: "QT-8-1",
  CREATE_POPUP_NOTIFY: "QT-8-2",
  EDIT_POPUP_NOTIFY: "QT-8-3",
  DELETE_POPUP_NOTIFY: "QT-8-4",
  // CATEGORY
  VIEW_CATEGORY: "QT-7-1",
  CREATE_CATEGORY: "QT-7-2",
  EDIT_CATEGORY: "QT-7-3",
  DELETE_CATEGORY: "QT-7-4",
  // CONFIG
  VIEW_CONFIG: "QT-9-1",
  EDIT_CONFIG: "QT-9-2",
  // AUTHORITY
  VIEW_AUTHORITY: "QT-10-1",
  CREATE_AUTHORITY: "QT-10-2",
  EDIT_AUTHORITY: "QT-10-3",
  DELETE_AUTHORITY: "QT-10-4",
  // Utility
  VIEW_UTILITY: "UT-1-1",
  CREATE_UTILITY: "UT-1-2",
  EDIT_UTILITY: "UT-1-3",
  DELETE_UTILITY: "UT-1-4",
  CREATE_UTILITY_GIFT: "UT-1-5",
  // WALLET
  VIEW_WALLET: "QT-11-1",
  CREATE_WALLET: "QT-11-2",
  EDIT_WALLET: "QT-11-3",
  DELETE_WALLET: "QT-11-4",
  DEPOSIT_WALLET: "QT-11-5",
  WITHDRAW_WALLET: "QT-11-6",
  // WALLETTRANSACTION
  VIEW_WALLETTRANSACTION: "QT-12-1",
  CREATE_WALLETTRANSACTION: "QT-12-2",
  EDIT_WALLETTRANSACTION: "QT-12-3",
  DELETE_WALLETTRANSACTION: "QT-12-4",
  // STREAM
  VIEW_STREAM: "QT-14-1",
  APPROVAL_STREAM: "QT-14-2",
  EDIT_STREAM: "QT-14-3",
  DELETE_STREAM: "QT-14-4",
  // INTRODUCE
  VIEW_INTRODUCE_CUSTOMER: "QT-15-1",
  // RATE
  VIEW_RATE: "QT-16-1",
  EDIT_RATE: "QT-16-3",
  DELETE_RATE: "QT-16-4",
  // NOTIFICATION
  VIEW_NOTIFICATION: "QT-17-1",
  // TRANSACTION
  VIEW_TRANSACTION: "GD-1-1",
  // CALL_TRANSACTION: "GD-1-2",
  EDIT_TRANSACTION: "GD-1-3",
  PHONE_TRANSACTION: "GD-1-4",
  CONFIRM_TRANSACTION: "GD-1-5",
  REPORT_TRANSACTION: "GD-1-6",
  SECURE_TRANSACTION: "GD-1-7",
  // SUPPLIER
  VIEW_SUPPLIER: "TH-1-1",
  CREATE_SUPPLIER: "TH-1-2",
  EDIT_SUPPLIER: "TH-1-3",
  DELETE_SUPPLIER: "TH-1-4",
  // CARDPRODUCT
  VIEW_CARDPRODUCT: "TH-2-1",
  CREATE_CARDPRODUCT: "TH-2-2",
  EDIT_CARDPRODUCT: "TH-2-3",
  DELETE_CARDPRODUCT: "TH-2-4",
  // BANK
  VIEW_BANK: "TH-3-1",
  CREATE_BANK: "TH-3-2",
  EDIT_BANK: "TH-3-3",
  DELETE_BANK: "TH-3-4",

  // CARD
  VIEW_CARD: "TH-5-1",
  ACTIVE_CARD: "TH-5-2",
  IMPORT_CARD: "TH-5-3",
  ACTION_CARD: "TH-5-4",
  DELETE_CARD: "TH-5-5",
  VIEW_CARD_CODE: "TH-5-6",
  //POST
  VIEW_POST: "TT-1-1",
  CREATE_POST: "TT-1-2",
  EDIT_POST: "TT-1-3",
  DELETE_POST: "TT-1-4",

  //THREAD
  VIEW_THREAD: "TG-1-1",
  RETRIEVE_THREAD: "TG-1-2",
  EDIT_THREAD: "TG-1-3",
  DELETE_THREAD: "TG-1-4",
  //CONFIRM
  VIEW_CONFIRM: "XN-1-1",
  EDIT_CONFIRM: "XN-1-2",
  //GROUP
  VIEW_GROUP: "GR-1-1",
  CREATE_GROUP: "GR-1-2",
  EDIT_GROUP: "GR-1-3",
  DELETE_GROUP: "GR-1-4",
  MEMBER_GROUP: "GR-1-5",
  VIEW_ALL_GROUP: "GR-1-6",
  //CONFIRM-BANK
  VIEW_VERIFY_BANK: "BA-1-1",
  EDIT_VERIFY_BANK: "BA-1-3",
  DELETE_VERIFY_BANK: "BA-1-4",
  // REPORT
  VIEW_REPORT: "QT-18-1",
  // TICKET
  VIEW_TICKET: "QT-19-1",
  EDIT_TICKET: "QT-19-2",
  DELETE_TICKET: "QT-19-3",
  // ACCUSE
  VIEW_ACCUSE: "QT-20-1",
  EDIT_ACCUSE: "QT-20-2",
  DELETE_ACCUSE: "QT-20-3",

  //AffiliateBooth
  VIEW_AFFILIATE_BOOTH: "AFB-1-1",
  CREATE_AFFILIATE_BOOTH: "AFB-1-2",
  EDIT_AFFILIATE_BOOTH: "AFB-1-3",
  DELETE_AFFILIATE_BOOTH: "AFB-1-4",

  //Affiliate Categories
  VIEW_AFFILIATE_CATEGORIES: "AFC-1-1",
  CREATE_AFFILIATE_CATEGORIES: "AFC-1-2",
  EDIT_AFFILIATE_CATEGORIES: "AFC-1-3",
  DELETE_AFFILIATE_CATEGORIES: "AFC-1-4",

  //Affiliate Product
  VIEW_AFFILIATE_PRODUCT: "AFP-1-1",
  APPROVE_AFFILIATE_PRODUCT: "AFP-1-2",

  // Approval File
  VIEW_APPROVAL_FILE: "APP-1-1",
  APPROVE_APPROVAL_FILE: "APP-1-2",

  // Wallet Draw
  VIEW_WALLET_DRAW: "WD-1-1",
  HANDEL_WALLET_DRAW: "WD-1-2",
  //credential
  VIEW_CREDENTIAL: "CR-1-1",
  EDIT_CREDENTIAL: "CR-1-2",
  // SHIPPING_PROVIDER
  VIEW_SHIPPING_PROVIDER: "SP-1-1",
  CREATE_SHIPPING_PROVIDER: "SP-1-2",
  EDIT_SHIPPING_PROVIDER: "SP-1-3",
  DELETE_SHIPPING_PROVIDER: "SP-1-4",
};
