export const SHOP_SCOPES = {
  ORDER_SELL: "OS-1-1",
  ORDER_BUY: "OB-1-1",
  PRODUCT: "PD-1-1",
  AFFILIATE: "AF-1-1",
  LIVE_STREAM: "LT-1-1",
  VIDEO: "VI-1-1",
  DEPOSITS: "DE-1-1",
  TRAININGS: "TR-1-1",
  NOTIFICATIONS: "NO-1-1",
  UTILITYS: "UT-1-1",
  MY_UTILITES: "MU-1-1",
  SHOP_VOUCHER: "SV-1-1",
  WALLET_TRANSACTION: "WT-1-1",
  SHOP_STAFF: "SS-1-1",
  ANALYTIC: "AN-1-1",
  SETTING: "SE-1-1",
  SUPPORT: "SP-1-1",
  CHAT_BOX: "CB-1-1",
  WALLET_DRAW: "WD-1-1",
};
export type ShopPermission =
  | typeof SHOP_SCOPES.ORDER_SELL
  | typeof SHOP_SCOPES.ORDER_BUY
  | typeof SHOP_SCOPES.PRODUCT
  | typeof SHOP_SCOPES.AFFILIATE
  | typeof SHOP_SCOPES.LIVE_STREAM
  | typeof SHOP_SCOPES.VIDEO
  | typeof SHOP_SCOPES.DEPOSITS
  | typeof SHOP_SCOPES.TRAININGS
  | typeof SHOP_SCOPES.NOTIFICATIONS
  | typeof SHOP_SCOPES.UTILITYS
  | typeof SHOP_SCOPES.MY_UTILITES
  | typeof SHOP_SCOPES.SHOP_VOUCHER
  | typeof SHOP_SCOPES.WALLET_TRANSACTION
  | typeof SHOP_SCOPES.SHOP_STAFF
  | typeof SHOP_SCOPES.ANALYTIC
  | typeof SHOP_SCOPES.SETTING
  | typeof SHOP_SCOPES.SUPPORT
  | typeof SHOP_SCOPES.CHAT_BOX
  | typeof SHOP_SCOPES.WALLET_DRAW;
